export var LanguageValues = {
    // Response Api texts
    'msg_accepted' : 'Exito',
    'msg_cancelled' : 'cancelado'   ,
    'msg_Error' : 'Error inesperado'   ,
    'msg_rejected' : 'El aviso ya fue enviado',
    'msg_title_msg_cancelled': 'Cancelado',
    'msg_title_msg_Error': 'Error inesperado',
    'msg_title_msg_rejected': 'rechazado',
    'msg_title_msg_accepted': 'éxito',
    'msg_accepted_fix': 'Aceptado',
    'msg_rejected_fix': 'El aviso ya fue enviado',
    'val_quer_art_msg_error' : 'Se presentó un error inesperado durante el proceso de carga del aviso. Por favor, inténtelo de nuevo.',
    'val_quer_art_msg_loading': 'Cargando...',
    'val_quer_art_lbl_headerSmall': 'Los campos con línea naranja son obligatorios.',
    'val_quer_art_lbl_btnCancel': 'Cancelar',
    'val_quer_art_lbl_btnFind': 'Buscar',
    'val_quer_art_lbl_btnFindAgain': 'Atras',
    'val_quer_art_lbl_btnXml': 'cargar otro archivo',
    'val_quer_art_lbl_btnPrint': 'imprimir',
    'val_quer_art_lbl_validationDetail': 'Detalle del resultado:',
    'val_quer_art_err_required': 'Campo requerido',
    'aut_ver_art_lbl_headerStrong': 'Ingrese aviso a cargar:',
    'aut_ver_art_lbl_headerSmall': 'Los campos con línea naranja son obligatorios.',
    'aut_ver_art_lbl_btnCancel': 'Cancelar',
    'aut_ver_art_lbl_btnFind': 'Cargar',
    'aut_ver_art_lbl_btnFindAgain': 'Cargar otro aviso',
    'aut_ver_art_lbl_validationWord_valid': 'Válido',
    'aut_ver_art_lbl_validationWord_rejected': 'El aviso ya fue enviado',
    'aut_ver_art_lbl_validationWord_error': 'Error',
    'aut_ver_art_lbl_validationDetail': 'Detalle del resultado:',
    'aut_ver_art_lbl_fileInput': 'Seleccione un archivo desde su equipo'

}
